[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "plan"

[dist.dependencies.apt]
libxi-dev = '*'
libxtst-dev = '*'

[dist.github-custom-runners]
global = "ubuntu-latest"
x86_64-unknown-linux-gnu = "ubuntu-latest"
aarch64-unknown-linux-gnu = "ubuntu-latest"
aarch64-pc-windows-msvc = "ubuntu-latest"
